name: Sync Fork

on:
  schedule:
    - cron: '0 10 * * *' # every day
  workflow_dispatch: # on button click

jobs:
  sync:

    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0
        with:
          owner: wl336
          base: master
          head: master
          ignore_fail: true

